name: Publish

on:
    push:
        tags:
            - '*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        strategy:
            matrix:
                node-version: [ 21.x ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Use Bun ${{ matrix.node-version }}
                uses: oven-sh/setup-bun@v2
            -   run: bun install
            -   run: bun run build
            -   run: bun run test
            -   run: bun publish --access public
                env:
                    NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
